matrix:
  include:

    - env:
        Name: Tool testing
      language: scala
      scala:
        - 2.11.11
      script:
        - sbt clean coverage test coverageReport &&
          sbt coverageAggregate
      after_success:
        - sbt coveralls
        - bash <(curl -s https://codecov.io/bash)

    - env:
        Name: Documentation testing
      language: python
      python: 2.7
      install: pip install -r docs/requirements.txt
      script: make -C docs/ html
