language: scala
scala:
  - 2.11.11
script:
  - "set -o pipefail && sbt -batch clean evicted biopetTest biopetTestReport | tee sbt.log"
  - |
    n=`grep -ce "\* com.github.biopet" sbt.log`
    if [ "$n" -ne "0" ]; then echo "ERROR: Found conflicting dependencies inside biopet"; exit 1; fi
  - "git diff --exit-code || (echo ERROR: Git changes detected, please regenerate the readme, create license headers and run scalafmt with: sbt biopetGenerateReadme headerCreate scalafmt && exit 1)"
